version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Application.sln && dotnet publish ./Application.sln -c Release -o ./obj/Docker/publish"
